baseURL = 'https://skatebuffalo.com/'
languageCode = 'en-us'
title = 'Skate Buffalo'
copyright = 'Corey Beres'
theme = 'ananke'

[params]
customCss = ['css/hero.css', 'css/flickity.min.css', 'css/flickity-fullscreen.css', 'css/flickity.extra.css']
customJs = ['js/flickity.pkgd.min.js', 'js/flickity-fullscreen.js']

