baseURL = 'https://skatebuffalo.com/'
locale = 'en-us'
title = 'Skate Buffalo'
copyright = 'Corey Beres'
theme = ['github.com/gohugo-ananke/ananke/v2']

[params]
customCss = ['css/hero.css', 'css/flickity.min.css', 'css/flickity-fullscreen.css', 'css/flickity.extra.css', 'css/leaflet.css', 'css/skatepark-map.css']
customJs = ['js/flickity.pkgd.min.js', 'js/flickity-fullscreen.js', 'js/leaflet.js', 'js/skatepark-map.js']

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/gohugo-ananke/ananke/v2'
