baseURL = 'https://skatebuffalo.com/'
locale = 'en-us'
title = 'Skate Buffalo'
copyright = 'Corey Beres'
theme = ['github.com/gohugo-ananke/ananke/v2']

[pagination]
  pagerSize = 9

[params]
customCss = ['css/hero.css', 'vendor/css/flickity.css', 'vendor/css/flickity-fullscreen.css', 'css/photos.css', 'vendor/css/leaflet.css', 'css/skatepark-map.css']
customJs = ['vendor/js/flickity.pkgd.min.js', 'vendor/js/flickity-fullscreen.js', 'vendor/js/leaflet.js', 'js/skatepark-map.js']

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/gohugo-ananke/ananke/v2'

[[module.mounts]]
  source = 'static'
  target = 'static'

[[module.mounts]]
  source = 'static/vendor/images'
  target = 'static/images'
